sudo: false

os:
  - linux

language: python
python:
  - 3.4
  - 3.5

#addons:

install:
#   - pip -r requirements.txt
   - pip install coveralls

script:
   - make clean
   - make
   - coverage run template-fbi-ucr.py

after_success:
   coveralls

